adding footer
Lucif3r-in/project-burrrah pull request #11
Opened 2024-01-04 06:00 UTC by ishita-1305

2024-01-07 03:40 UTC, ashutosh-rath02 commented
![image](https://github.com/ashutosh-rath02/project-burrrah/assets/85403534/cb841fe6-bc42-4c39-bbc3-d3722df0314a)
- There is alignment issues.
- Improve the project structure as suggested earlier
@ishita-1305

2024-02-07 19:03 UTC, Srish-ty requested changes
also delete navbar2.jsx 
and yarn.lock files

2024-02-07 19:03 UTC, Srish-ty commented on src/app/Homepage.jsx
> +import { Navbar } from './components/marginals/navbar2'
change to 
import { Navbar } from './components/marginals/Navbar'

2024-02-07 19:03 UTC, Srish-ty commented on src/app/signup/page.jsx
> +import { Navbar } from '../components/marginals/navbar2'
make changes
import { Navbar } from './components/marginals/Navbar'

2024-02-08 08:36 UTC, merged